FROM python:3.10-slim-bookworm

RUN apt-get update && apt-get install build-essential git -y
RUN pip install prometheus-client grpcio-health-checking google-cloud-dataproc
RUN pip install --no-cache-dir -U flytekit \
    git+https://github.com/nerochung/flytekit.git#subdirectory=plugins/flytekit-dataproc \
    && apt-get clean autoclean \
    && apt-get autoremove --yes \
    && rm -rf /var/lib/{apt,dpkg,cache,log}/ \
    && :

CMD pyflyte serve agent --port 8000
